# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "lightning"
languages = ["CXX"]

[options]
LIGHTING_TESTS = true

[conditions]
emscripten = "EMSCRIPTEN"
tests = "LIGHTING_TESTS"
x86_64 = "CMAKE_SYSTEM_PROCESSOR MATCHES \"(amd64)|(AMD64)\""

[target.libli]
type = "static"
link-libraries = ["Zydis"]
include-directories = ["include"]
compile-features = ["cxx_std_20"]
sources = [
    "src/**.cpp",
    "src/**.hpp",
    "include/**.hpp",
]

[target.li]
type = "executable"
link-libraries = ["libli"]
sources = ["repl.cpp"]
emscripten.link-options = [
    "-sEXPORTED_RUNTIME_METHODS=ccall,cwrap",
    "-sEXTRA_EXPORTED_RUNTIME_METHODS=ccall,cwrap",
    "-sEXPORTED_FUNCTIONS=_main,_runscript",
]

[[install]]
targets = ["li"]
destination = "bin"

[[install]]
condition = "emscripten"
files = ["$<TARGET_FILE_DIR:li>/li.wasm"]
destination = "bin"

[subdir.zydis]

[subdir.tests]
condition = "tests"