; Win64 MASM implementation. Offsets mirror LI_CONTEXT_WIN64_* in util/context.hpp.
OPTION CASEMAP:NONE

LI_CONTEXT_WIN64_RBX_OFFSET   EQU 0
LI_CONTEXT_WIN64_RBP_OFFSET   EQU 8
LI_CONTEXT_WIN64_RDI_OFFSET   EQU 16
LI_CONTEXT_WIN64_RSI_OFFSET   EQU 24
LI_CONTEXT_WIN64_R12_OFFSET   EQU 32
LI_CONTEXT_WIN64_R13_OFFSET   EQU 40
LI_CONTEXT_WIN64_R14_OFFSET   EQU 48
LI_CONTEXT_WIN64_R15_OFFSET   EQU 56
LI_CONTEXT_WIN64_RSP_OFFSET   EQU 64
LI_CONTEXT_WIN64_PC_OFFSET    EQU 72
LI_CONTEXT_WIN64_MXCSR_OFFSET EQU 80
LI_CONTEXT_WIN64_X87CW_OFFSET EQU 84
LI_CONTEXT_WIN64_XMM6_OFFSET  EQU 96
LI_CONTEXT_WIN64_XMM7_OFFSET  EQU 112
LI_CONTEXT_WIN64_XMM8_OFFSET  EQU 128
LI_CONTEXT_WIN64_XMM9_OFFSET  EQU 144
LI_CONTEXT_WIN64_XMM10_OFFSET EQU 160
LI_CONTEXT_WIN64_XMM11_OFFSET EQU 176
LI_CONTEXT_WIN64_XMM12_OFFSET EQU 192
LI_CONTEXT_WIN64_XMM13_OFFSET     EQU 208
LI_CONTEXT_WIN64_XMM14_OFFSET     EQU 224
LI_CONTEXT_WIN64_XMM15_OFFSET     EQU 240
LI_CONTEXT_WIN64_STACKBASE_OFFSET EQU 256
LI_CONTEXT_WIN64_STACKLIMIT_OFFSET EQU 264

EXTERN li_context_run:PROC
PUBLIC context_switch
PUBLIC li_context_bootstrap

.code
ALIGN 16
context_switch PROC FRAME
	.ENDPROLOG
	mov QWORD PTR [rcx + LI_CONTEXT_WIN64_RBX_OFFSET], rbx
	mov QWORD PTR [rcx + LI_CONTEXT_WIN64_RBP_OFFSET], rbp
	mov QWORD PTR [rcx + LI_CONTEXT_WIN64_RDI_OFFSET], rdi
	mov QWORD PTR [rcx + LI_CONTEXT_WIN64_RSI_OFFSET], rsi
	mov QWORD PTR [rcx + LI_CONTEXT_WIN64_R12_OFFSET], r12
	mov QWORD PTR [rcx + LI_CONTEXT_WIN64_R13_OFFSET], r13
	mov QWORD PTR [rcx + LI_CONTEXT_WIN64_R14_OFFSET], r14
	mov QWORD PTR [rcx + LI_CONTEXT_WIN64_R15_OFFSET], r15
	lea rax, [rsp + 8]
	mov QWORD PTR [rcx + LI_CONTEXT_WIN64_RSP_OFFSET], rax
	mov rax, QWORD PTR [rsp]
	mov QWORD PTR [rcx + LI_CONTEXT_WIN64_PC_OFFSET], rax
	stmxcsr DWORD PTR [rcx + LI_CONTEXT_WIN64_MXCSR_OFFSET]
	fnstcw WORD PTR [rcx + LI_CONTEXT_WIN64_X87CW_OFFSET]
	movdqu XMMWORD PTR [rcx + LI_CONTEXT_WIN64_XMM6_OFFSET], xmm6
	movdqu XMMWORD PTR [rcx + LI_CONTEXT_WIN64_XMM7_OFFSET], xmm7
	movdqu XMMWORD PTR [rcx + LI_CONTEXT_WIN64_XMM8_OFFSET], xmm8
	movdqu XMMWORD PTR [rcx + LI_CONTEXT_WIN64_XMM9_OFFSET], xmm9
	movdqu XMMWORD PTR [rcx + LI_CONTEXT_WIN64_XMM10_OFFSET], xmm10
	movdqu XMMWORD PTR [rcx + LI_CONTEXT_WIN64_XMM11_OFFSET], xmm11
	movdqu XMMWORD PTR [rcx + LI_CONTEXT_WIN64_XMM12_OFFSET], xmm12
	movdqu XMMWORD PTR [rcx + LI_CONTEXT_WIN64_XMM13_OFFSET], xmm13
	movdqu XMMWORD PTR [rcx + LI_CONTEXT_WIN64_XMM14_OFFSET], xmm14
	movdqu XMMWORD PTR [rcx + LI_CONTEXT_WIN64_XMM15_OFFSET], xmm15
	mov rax, QWORD PTR gs:[8]
	mov QWORD PTR [rcx + LI_CONTEXT_WIN64_STACKBASE_OFFSET], rax
	mov rax, QWORD PTR gs:[16]
	mov QWORD PTR [rcx + LI_CONTEXT_WIN64_STACKLIMIT_OFFSET], rax

	ldmxcsr DWORD PTR [rdx + LI_CONTEXT_WIN64_MXCSR_OFFSET]
	fldcw WORD PTR [rdx + LI_CONTEXT_WIN64_X87CW_OFFSET]
	movdqu xmm6, XMMWORD PTR [rdx + LI_CONTEXT_WIN64_XMM6_OFFSET]
	movdqu xmm7, XMMWORD PTR [rdx + LI_CONTEXT_WIN64_XMM7_OFFSET]
	movdqu xmm8, XMMWORD PTR [rdx + LI_CONTEXT_WIN64_XMM8_OFFSET]
	movdqu xmm9, XMMWORD PTR [rdx + LI_CONTEXT_WIN64_XMM9_OFFSET]
	movdqu xmm10, XMMWORD PTR [rdx + LI_CONTEXT_WIN64_XMM10_OFFSET]
	movdqu xmm11, XMMWORD PTR [rdx + LI_CONTEXT_WIN64_XMM11_OFFSET]
	movdqu xmm12, XMMWORD PTR [rdx + LI_CONTEXT_WIN64_XMM12_OFFSET]
	movdqu xmm13, XMMWORD PTR [rdx + LI_CONTEXT_WIN64_XMM13_OFFSET]
	movdqu xmm14, XMMWORD PTR [rdx + LI_CONTEXT_WIN64_XMM14_OFFSET]
	movdqu xmm15, XMMWORD PTR [rdx + LI_CONTEXT_WIN64_XMM15_OFFSET]
	mov r8, QWORD PTR [rdx + LI_CONTEXT_WIN64_STACKBASE_OFFSET]
	mov r9, QWORD PTR [rdx + LI_CONTEXT_WIN64_STACKLIMIT_OFFSET]
	mov rax, QWORD PTR [rdx + LI_CONTEXT_WIN64_PC_OFFSET]
	mov rbx, QWORD PTR [rdx + LI_CONTEXT_WIN64_RBX_OFFSET]
	mov rbp, QWORD PTR [rdx + LI_CONTEXT_WIN64_RBP_OFFSET]
	mov rdi, QWORD PTR [rdx + LI_CONTEXT_WIN64_RDI_OFFSET]
	mov rsi, QWORD PTR [rdx + LI_CONTEXT_WIN64_RSI_OFFSET]
	mov r12, QWORD PTR [rdx + LI_CONTEXT_WIN64_R12_OFFSET]
	mov r13, QWORD PTR [rdx + LI_CONTEXT_WIN64_R13_OFFSET]
	mov r14, QWORD PTR [rdx + LI_CONTEXT_WIN64_R14_OFFSET]
	mov r15, QWORD PTR [rdx + LI_CONTEXT_WIN64_R15_OFFSET]
	mov QWORD PTR gs:[8], r8
	mov QWORD PTR gs:[16], r9
	mov rsp, QWORD PTR [rdx + LI_CONTEXT_WIN64_RSP_OFFSET]
	push rax
	ret
context_switch ENDP

ALIGN 16
li_context_bootstrap PROC FRAME
	.ENDPROLOG
	mov rcx, r12
	mov rdx, r13
	mov r8, r14
	mov r9, r15
	jmp li_context_run
li_context_bootstrap ENDP

END
